enum KeyRedisPrefix {
  fromBlockNumber = "from_block_number",
  ohlcPrefix = "ohlc",
  tokenRouteMapping = "token_route_mapping",
  toBlockNumber = "to_block_number",
  blockNumber = "block_number",
  tradeHistory = "trade_history",
  lastPrice24h = "last_price_24h",
  price = "price",
  tokenAdmin = "token_admin",
  searchToken = "search_token",
  priceToken = "price_token",
  lastVolume24h = "last_volume_24h",
  priceChange = "price_change",
  priceTokenVNDC = "price_token_vndc",
  priceInfo = "price_info",
  hashmapToken = "hashmap_token",
  increaseTransactionId = "increase_transaction_id",
  dexScanner = "dex_scanner",
  eventLatest = "event_latest",
}
const DataKey = {
  event: "e",
  ask: "a",
  bid: "b",
  lastPrice: "p",
  lastPrice24h: "ld",

  high: "h",
  low: "l",
  open: "o",
  close: "c",
  high1h: "hh",
  low1h: "lh",
  totalBaseVolume: "vb",
  totalQuoteVolume: "vq",
  lastQuantity: "lq",
  lastQuoteQty: "lQ",
  symbol: "s",
  quoteAssetId: "qi",
  baseAssetId: "bi",
  baseAsset: "b",
  quoteAsset: "q",
  up: "u",
  lastHistoryId: "li",
  timestamp: "t",
  avgVolume: "av",

  price1h: "ph",
  price24h: "ld",
  price1w: "pw",
  price1m: "p1m",
  price3m: "p3m",
  priceY: "py",
  lowY: "ly",
  highY: "hy",
  ath: "ath",
  cmcId: "cid",
  views: "vc",
  marketCap: "mc",
  supply: "sp",
};
enum Period {
  OneMinute = "1m",
  FiveMinutes = "5m",
  FifteenMinutes = "15m",
  ThirtyMinutes = "30m",
  OneHour = "1h",
  FourHours = "4h",
  OneDay = "1d",
  OneWeek = "1w",
}

enum Chain {
  bsc = "bsc",
}
export { KeyRedisPrefix, DataKey, Period, Chain };
